# Generated by Django 4.1.7 on 2023-02-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_lineitem_delete_lineitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='reporting.invoice'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='reporting.job'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='reporting.payment'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='self_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='reporting.lineitem'),
        ),
    ]
