# Generated by Django 4.1.7 on 2023-03-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_lineitem_invoice_alter_lineitem_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='business',
            field=models.ForeignKey(db_column='business', on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='reporting.business'),
        ),
    ]
