# Generated by Django 4.1.7 on 2023-03-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_job_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='business',
            field=models.ForeignKey(db_column='business', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='reporting.business'),
        ),
    ]
