# Generated by Django 4.1.7 on 2023-03-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_alter_invoice_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='job',
            field=models.ForeignKey(db_column='job', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lineitem', to='reporting.job'),
        ),
    ]
