# Generated by Django 4.1.7 on 2023-03-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_alter_lineitem_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='invoice',
            field=models.ForeignKey(db_column='invoice', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lineitem', to='reporting.invoice'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='self_item',
            field=models.ForeignKey(db_column='self_item', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoiceditem', to='reporting.lineitem'),
        ),
    ]
